server:
  port: 8001

spring:
  profiles:
    active: debug
  application:
    name: "springbucks"
  #    数据库配置
  datasource:
    username: root
    password: dev
    url: jdbc:mysql://localhost:3306/devtest?serverTimezone=Asia/Shanghai
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: admin
  #开启mybatis驼峰式命名规则自动转换
  map-underscore-to-camel-case: false

